### ISSUE TITLE
Add GitHub link to pkgdown website

### ISSUE THREAD

**Issue by peterdesmet** [lifewatch/mregions2#10]
Currently there is no link from the website (https://lifewatch.github.io/mregions2/) to the repository. I think it is included automatically, if you specify a `URL` or `BugReports`:

https://github.com/frictionlessdata/frictionless-r/blob/b6d330858f9c3ce1bc95e1c23520766f0ffea3d5/DESCRIPTION#L24-L26

**Comment by salvafern** [comment]
Thanks @peterdesmet, fixed on 6d1dbbe8a99b53f51d85047d0aea47fbb132348d
