### ISSUE TITLE
Use a single function `mr_gaz_records_by_name()`

### ISSUE THREAD

**Issue by peterdesmet** [lifewatch/mregions2#11]
Currently there are two functions:

```
mr_gaz_records_by_name()
mr_gaz_records_by_names()
```

I would suggest to only have a single function `mr_gaz_records_by_name()`, but where the `name` parameter accepts a string or vector of strings. In both cases, a tibble would be returned.

**Comment by salvafern** [comment]
Indeed confusing at the moment. There are two different [services ](https://marineregions.org/gazetteer.php?p=webservices&type=rest)for requesting one single name (`getGazetteerRecordsByName`) or multiple (`getGazetteerRecordsByNames`), hence the two services.

To check whether change the webservice at origin or at the R package level.

Thanks for the heads up @peterdesmet !

**Comment by bart-v** [comment]
I don't see any confusion, but OK...
Please change it in the R package

**Comment by salvafern** [comment]
Both functions will stay as I want them to be as close as possible to the gazetteer REST web services.

But I will create a higher level function on top that will be more user friendly. More info coming soon.
