### ISSUE TITLE
EEZs returned by mrp_get are rotated? Declare SRS explicitely

### ISSUE THREAD

**Issue by jflowernet** [lifewatch/mregions2#19]
Hi,
First, thanks for the excellent `mregions2` package.

I've just started having issues retrieving EEZ data using `mrp_get`. I'm including a reprex below, but in short, the EEZ data retrieved seems to be rotated 90 degrees clockwise (I think). 

I don't know if it is related, but calling `mregions2::mrp_get` without loading the package first (`library(mregions2)`) results in an error (see reprex). I've found that this is because `mrp_list` is not available for `mrp_get` to reference.

I've tried uninstalling and reinstalling the `mregions2` package, and restarting R and my computer. Any help diagnosing the problem would be greatly appreciated!

``` r
#mrp_get function won't work without loading the mregions2 library
mregions2::mrp_get("eez", cql_filter = "territory1 = 'Azores'")
#> Error in mregions2::mrp_get("eez", cql_filter = "territory1 = 'Azores'"): object 'mrp_list' not found

library(mregions2)
azores <- mrp_get("eez", cql_filter = "territory1 = 'Azores'")


plot(azores[1])
```

![](https://i.imgur.com/FmLTreN.png)

``` r

#plot seems to be rotated 90 degrees clockwise??

azores
#> Simple feature collection with 1 feature and 31 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 33.58636 ymin: -35.58558 xmax: 43.06483 ymax: -20.59917
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 32
#>   mrgid geoname    mrgid_ter1 pol_type mrgid_sov1 territory1 iso_ter1 sovereign1
#>   <int> <chr>           <int> <chr>         <int> <chr>      <chr>    <chr>     
#> 1  8361 Portugues…       2454 200NM          2243 Azores     <NA>     Portugal  
#> # ℹ 24 more variables: mrgid_ter2 <int>, mrgid_sov2 <int>, territory2 <chr>,
#> #   iso_ter2 <chr>, sovereign2 <chr>, mrgid_ter3 <int>, mrgid_sov3 <int>,
#> #   territory3 <chr>, iso_ter3 <chr>, sovereign3 <chr>, x_1 <dbl>, y_1 <dbl>,
#> #   mrgid_eez <int>, area_km2 <int>, iso_sov1 <chr>, iso_sov2 <chr>,
#> #   iso_sov3 <chr>, un_sov1 <dbl>, un_sov2 <dbl>, un_sov3 <dbl>, un_ter1 <dbl>,
#> #   un_ter2 <dbl>, un_ter3 <dbl>, geometry <POLYGON [°]>

sessionInfo()
#> R version 4.3.0 (2023-04-21)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Linux Mint 20.3
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
#>  [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
#>  [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Australia/Brisbane
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mregions2_1.0.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] dplyr_1.1.2        compiler_4.3.0     tidyselect_1.2.0   reprex_2.0.2      
#>  [5] Rcpp_1.0.10        yaml_2.3.7         fastmap_1.1.1      R6_2.5.1          
#>  [9] generics_0.1.3     curl_5.0.0         classInt_0.4-9     httr2_0.2.2       
#> [13] sf_1.0-13          knitr_1.43         backports_1.4.1    checkmate_2.1.0   
#> [17] tibble_3.2.1       units_0.8-1        DBI_1.1.3          pillar_1.9.0      
#> [21] rlang_1.1.0        utf8_1.2.3         xfun_0.39          fs_1.6.2          
#> [25] cli_3.6.1          withr_2.5.0        magrittr_2.0.3     class_7.3-22      
#> [29] digest_0.6.31      grid_4.3.0         rstudioapi_0.14    rappdirs_0.3.3    
#> [33] lifecycle_1.0.3    vctrs_0.6.1        KernSmooth_2.23-21 proxy_0.4-27      
#> [37] evaluate_0.21      glue_1.6.2         fansi_1.0.4        e1071_1.7-13      
#> [41] rmarkdown_2.21     tools_4.3.0        pkgconfig_2.0.3    htmltools_0.5.5
```

<sup>Created on 2023-06-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here is a screenshot of Azores' EEZ from marineregions.org for reference: 
![image](https://github.com/lifewatch/mregions2/assets/17166483/7c38d088-a44e-485b-a484-24f3808112fb)

**Comment by jflowernet** [comment]
I tried downgrading to R version 4.2.0 and reinstalling all necessary packages to see if that was the problem, but I still have the same issue.

**Comment by jflowernet** [comment]
And doing a bit more investigation, this seems to be due to commits to `mregions2`since 14th March: if I roll back to `mregions2@387fb12` (`devtools::install_github("lifewatch/mregions2@387fb12)`, I don't have the same issues as described above, but the object returned by the `mrp_get` call is a `MULTISURFACE`:
``` r
azores <- mregions2::mrp_get("eez", cql_filter = "territory1 = 'Azores'")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> Error in (function (msg)  : ParseException: Unknown WKB type 12

azores
#> Simple feature collection with 1 feature and 31 fields
#> Geometry type: MULTISURFACE
#> Dimension:     XY
#> Bounding box:  xmin: -35.58558 ymin: 33.58636 xmax: -20.59917 ymax: 43.06483
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 32
#>   mrgid geoname    mrgid_ter1 pol_type mrgid_sov1 territory1 iso_ter1 sovereign1
#> * <int> <chr>           <int> <chr>         <int> <chr>      <chr>    <chr>     
#> 1  8361 Portugues…       2454 200NM          2243 Azores     <NA>     Portugal  
#> # ℹ 24 more variables: mrgid_ter2 <int>, mrgid_sov2 <int>, territory2 <chr>,
#> #   iso_ter2 <chr>, sovereign2 <chr>, mrgid_ter3 <int>, mrgid_sov3 <int>,
#> #   territory3 <chr>, iso_ter3 <chr>, sovereign3 <chr>, x_1 <dbl>, y_1 <dbl>,
#> #   mrgid_eez <int>, area_km2 <int>, iso_sov1 <chr>, iso_sov2 <chr>,
#> #   iso_sov3 <chr>, un_sov1 <dbl>, un_sov2 <dbl>, un_sov3 <dbl>, un_ter1 <dbl>,
#> #   un_ter2 <dbl>, un_ter3 <dbl>, the_geom <MULTISURFACE [°]>

plot(azores[1])
#> Error in xy.coords(x, y, xlabel, ylabel, log): 'x' is a list, but does not have components 'x' and 'y'
```

<sup>Created on 2023-06-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by salvafern** [comment]
Hi @jflowernet 

Many thanks for the interest in mregions2 and raising these issues! 
FYI the package is currently under review at rOpenSci (https://github.com/ropensci/software-review/issues/590), your comments are well timed.

1. I will look into not needing to load `mregions2` to use `mrp_get`. The obvious solution would be to add `mregions2::mrp_list` but this probably it is not the most correct way, need to investigate best practices guidelines.
2. Indeed it is also rotated for me! I suspect this is because the geoserver behind `mregions2` was recently updated. A possible solution could be https://r-spatial.github.io/sf/articles/sf3.html#affine-transformations - I will check further

I would refrain from using a commit older than https://github.com/lifewatch/mregions2/commit/e6d533dab8eb768fc623c7b37477e6aa38deb708 as I changed the whole back-end to make our own WFS calls instead. Previously it used ows4R, but we prefer to have full control over the WFS calls. 
Indeed the default geometry are MULTISURFACE's. Some guidelines to turn into less exotic geometries are here: https://inbo.github.io/tutorials/tutorials/spatial_wfs_services/#example-2-filter-by-attributes. 
But this should not be neccesary in the current stage - just need to find a way to rotate.

I will be on leave soon and until 2023-07-24; will try to fix before but if not it will have to be later. Otherwise feel free to PR.

**Comment by jflowernet** [comment]
Hi @salvafern 

Many thanks for your response - I'm glad it wasn't just a problem with my system!

1. Agree that the simplest way is to use `mregions2::mrp_list` where it is called. The only reason I noticed is because I am creating an R package that has uses `mregions2::mrp_get` to get EEZs and it returns an error since `mrp_list` is not loaded since I'm not loading the whole `mregions2` package. This is not a big issue for me as I can always add `mrp_list <- mregions2::mrp_list` before I do the `mrp_get` call.
2. I was looking at options for rotating the resulting sf object, and also different options for `mrp_get`. I noticed that the issue with a rotated returned object is only for shapefiles - if I modify the url used within `mrp_get` to have `outputFormat = "JSON"` the .json file is not rotated! This would also seem to be an easier option as it avoids having to unzip the downloaded shapefile zip file. Is there any reason the function shouldn't use a Geojson?

If the Geojson option seems reasonable to you, I would be happy to do a PR as it should be some pretty minor modifications to the code,

**Comment by LennertSchepers** [comment]
It seems to be related to our geoserver as it persists outside the mregions2 package. It also occurs if you just download the two WFS requests.

http://geo.vliz.be/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&cql_filter=territory1=%27Azores%27&outputFormat=SHAPE-ZIP -> swapped x and y coordinates

http://geo.vliz.be/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&cql_filter=territory1=%27Azores%27&outputFormat=json -> ok result


```r
library(sf)
library(mapview)


# json
json <- st_read(dsn = 'http://geo.vliz.be/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&cql_filter=territory1=%27Azores%27&outputFormat=json')
mapview(json)

# shape-zip
download.file('http://geo.vliz.be/geoserver/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&cql_filter=territory1=%27Azores%27&outputFormat=SHAPE-ZIP',
              destfile = 'shp_zip')
unzip('shp_zip')
shp <- st_read('eez.shp')
mapview(json, col.regions = 'green') + mapview(shp)

```

![image](https://github.com/lifewatch/mregions2/assets/6145889/759d5231-4a68-43b7-baf5-9f740b966754)


@bart-v any idea?

**Comment by bart-v** [comment]
Sigh...known issue
https://docs.geoserver.org/2.22.x/en/user/services/wfs/axis_order.html
- you don't provide an EPSG ...
- your cql filter contains "=" this seems to work, but is not properly URL escaped

**Comment by salvafern** [comment]
True, adding the srs fixes it. I will add this in the package - all layers are assumed to be EPGS:
```
geo.vliz.be/geoserver/ows?service=WFS&srsName=EPSG:4326&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&cql_filter=territory1%3D%27Azores%27&outputFormat=SHAPE-ZIP
```
![image](https://github.com/lifewatch/mregions2/assets/54405067/0858e981-dfc6-4e02-b6b7-aab8ade1702e)


@jflowernet regarding why shp -> We chose to use shapefiles to improve performance. It doesn't make a big difference if you use a filter or requesting a data product with a relatively simple geometry (e.g. high seas). But it does for the EEZs, that have a high complex geometry mostly because we use a very detailed coastline. 

As the main objective of `mrp_get()` is to download the full product at once, we wanted to prioritize performance via using shapefiles as they come in zipped, but we also added a cache system to avoid repetitive requests and write to disk instead of loading on memory. The CQL/OGC filters are a nice addition but not the main purpose of this function.

Quick benchmark geojson vs shape-zip

```r
library(mregions2)
library(sf)

system.time({
  json <- st_read(dsn = 'http://geo.vliz.be/geoserver/ows?service=WFS&srsName=EPSG:4326&version=2.0.0&request=GetFeature&typeName=MarineRegions:eez&&outputFormat=json')
})
#>    user  system elapsed 
#>   55.30   69.79  223.14

system.time({
  shp <- mrp_get("eez")
})
#>    user  system elapsed 
#>   21.94    2.68   88.58
```
<sup>Created on 2023-06-28 with [reprex v2.0.2](https://reprex.tidyverse.org/)</sup>

Note individual EEZs can be done via the gazetteer `gaz_search('Portuguese Exclusive Economic Zone (Azores') %>% gaz_geometry()`. Although there are more attributes available when accessing via `mrp_get()`. Depending on the purpose it might be more interesting using one or another.

May I ask what is the purpose of the R package you are writing? 😄

**Comment by bart-v** [comment]
Next time make the commit message contain "fixes #19" :)
https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by jflowernet** [comment]
@salvafern and your colleagues: many thanks for figuring this out and fixing it quickly! And thanks for the note about other options for querying specific EEZs.

The R package I'm writing is essentially some functions to enable the user to quickly and simply get data for use in spatial prioritization using the R package [prioritizr](https://github.com/prioritizr/prioritizr/). It uses `mrp_get` to pull down an EEZ for an area of interest that can then be passed to other functions in the package to get data for that area. It currently includes options for pulling bathymetry (from [ETOPO 2022](https://www.ncei.noaa.gov/products/etopo-global-relief-model)), geomorphology features, some cold water coral data, and uses the BioOracle data to create localized 'ecoregions'. Happy to discuss more, and will let you know when we make the repo public.

**Comment by salvafern** [comment]
That's really interesting, thanks! Let us know when it is public.
FYI we also host Bio-Oracle. We are currently working on publishing the third version, which should be out soon. For the time being we won't publish this third version in [`sdmpredictors`](https://github.com/lifewatch/sdmpredictors) but in a new R package, and also in an ERDDAP server that can be read with [`rerddap`](https://docs.ropensci.org/rerddap/). We will make some advertisement when is out :)

**Comment by jflowernet** [comment]
Thanks for the updates about Bio-Oracle; it's such a great resource and I have used `sdmpredictors`. Look forward to the 3rd version!
