### ISSUE TITLE
Cannot query the Global Oceans data name column using `mrp_col_unique("goas", "name")` 

### ISSUE THREAD

**Issue by jflowernet** [lifewatch/mregions2#23]
The title pretty much sums up the issue, and reprex below gives more details

I'm using the current version of `mregions2`: lifewatch/mregions2@c5269b6

``` r
library(mregions2)

#this fails
mrp_col_unique("goas", "name")
#> Error in (function (layer, colname) : Assertion on 'colname' failed: Must be element of set {'latitude','longitude','min_y','min_x','max_y','max_x','area_km2'}, but is 'name'.

#but there is a name column since we can query with it:
mrp_get("goas", cql_filter = "name = 'South Pacific Ocean'")
#> Simple feature collection with 1 feature and 8 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -180 ymin: -60 xmax: 180 ymax: 3.391144
#> Geodetic CRS:  WGS 84
#>                  name  latitude longitude min_y    min_x   max_y     max_x
#> 1 South Pacific Ocean -30.09612 -143.0609   -60 130.1113 3.39114 -67.26667
#>   area_km2                       geometry
#> 1 90147400 MULTIPOLYGON (((-70.93199 -...

#other column values for goas can be found:
mrp_col_unique("goas", "latitude")
#>  [1] "-27.27272" "-30.09612" "-33.73758" "-68.03985" "26.95013"  "31.77621" 
#>  [7] "38.13065"  "5.62943"   "58.78478"  "79.14792"
```

<sup>Created on 2024-05-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by salvafern** [comment]
@bart-v This is an issue at geoserver. The request does not return "name". Could you have a look?

https://geo.vliz.be/geoserver/ows?service=wfs&version=2.0.0&request=DescribeFeatureType&typeName=MarineRegions:goas
```
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:MarineRegions="geo.vliz.be/MarineRegions" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="geo.vliz.be/MarineRegions">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://geo.vliz.be/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="goasType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="latitude" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="longitude" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="min_y" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="min_x" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="max_y" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="max_x" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="area_km2" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="the_geom" nillable="true" type="gml:MultiSurfacePropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="goas" substitutionGroup="gml:AbstractFeature" type="MarineRegions:goasType"/>
</xsd:schema>

```

**Comment by salvafern** [comment]
@jflowernet thanks for raising this issue. While we get a better fix you could look directly at the underlying service:

https://geo.vliz.be/geoserver/ows?service=wfs&version=2.0.0&request=GetPropertyValue&typeNames=MarineRegions:goas&valueReference=name

The R function `mrp_col_unique()` fails cause it has a check on place to only allow values returned by `mrp_colnames()`. However as "name" is an attribute of the layer, the underlying service works fine, even the R function if you bypass this check. But I prefer that we fix the problem at the root in geoserver rather than adding an exception for this issue. We will look into it.

**Comment by bart-v** [comment]
This looks like a Geoserver bug, since renaming `name` to `name1` makes it available

The quick fix is to use JSON output
https://geo.vliz.be/geoserver/ows?service=wfs&version=2.0.0&request=DescribeFeatureType&typeNames=MarineRegions:goas&outputFormat=application/json

**Comment by bart-v** [comment]
Apparently, it's not a bug, but a GML feature/config setting:
https://gis.stackexchange.com/questions/388394/geoserver-describefeaturetype-response-missing-attribute-for-gml-only

This has been fixed

**Comment by jflowernet** [comment]
Excellent, many thanks. I can confirm that `mrp_col_unique("goas", "name")` returns the names correctly at my end now
