### ISSUE TITLE
Github actions, some potential workarounds

### ISSUE THREAD

**Issue by jooolia** [lifewatch/mregions2#24]
Dear @salvafern ,
As discussed in https://github.com/ropensci/software-review/issues/590 there have been some difficulties with the testing of the package on Github Actions. 

In my fork of the repo I have found a few workaround and I will make a pull request based on this work. We can discuss further in the PR. 

Thanks, Julia

**Comment by mpadge** [comment]
@jooolia @salvafern The pkgcheck-action failures look like a cache issue to me, and I can't repeat in the container itself. I've nevertheless updated our Docker container in the commit linked above which should fix, so you can leave the `pkgcheck.yaml` file in place.

**Comment by jooolia** [comment]
Hi @mpadge, thanks for the check. I have tried to test this out but did not have any luck (you can see the run here: https://github.com/jooolia/mregions2/actions/runs/9196705137/job/25295406943), any thoughts on what I missed?
Thanks, Julia

**Comment by mpadge** [comment]
Ah, thanks @jooolia, that was enough to diagnose the problem at least. Can you please trigger the workflow again on your fork? Hopefully it should work now ... :crossed_fingers:

**Comment by jooolia** [comment]
Hi @mpadge, thanks, it is still failing. It seems to be similar to the failure with R-CMD-CHECK where we have the dependency temporary workaround in place.

**Comment by salvafern** [comment]
Hi @jooolia and @mpadge , thanks a lot for having a look at this issue! As in https://github.com/ropensci-review-tools/pkgcheck-action/issues/48#issuecomment-2134551849 I assume this issue can be closed as the problem should be fixed at `pak`. For the time being  @jooolia 's PR seems to fix the CI. Feel free to reopen otherwise!
