### ISSUE TITLE
Codecov CI failing after moving to rOpenSci

### ISSUE THREAD

**Issue by salvafern** [lifewatch/mregions2#27]
Hi @jooolia :wave: I'm finishing off the last details of the publication of this package. I am struggling to fix the codecov pipeline (See currently not working: https://app.codecov.io/gh/ropensci/mregions2?branch=main ; failed pipeline https://github.com/ropensci/mregions2/actions/runs/9549292710 )

Could I ask for support to fix this? I'm not well versed in codecov.

Triggered by https://github.com/ropensci/software-review/issues/590#issuecomment-2156724256

**Comment by bart-v** [comment]
@salvafern I think we need to add/update the `Repository upload token` from https://app.codecov.io/github/ropensci/mregions2/config/general
I can't do this now, can you give me admin access to [mregions2](https://github.com/ropensci/mregions2) (on github)?

**Comment by salvafern** [comment]
I gave you admin access :+1:

**Comment by bart-v** [comment]
Thanks
Codecov CI has been fixed
