### ISSUE TITLE
Some sources give 404 error at http request

### ISSUE THREAD

**Issue by lottepohl** [lifewatch/mregions2#3]
Commit 54fd249b63cac02d58f23d8d740adc3fb371c490 include the webservices [getGazetteerSources](https://marineregions.org/gazetteer.php?p=webservices&type=rest#!/getGazetteerSources) and [getGazetteerRecordsBySource](https://marineregions.org/gazetteer.php?p=webservices&type=rest#!/getGazetteerRecordsBySource/getGazetteerRecordsBySource).
Some sources are sentences and give a http 404 status code.

``` r
library("mregions2")
source_success <- mr_gaz_info(info = "sources")$source[57]
source_success <- as.character(source_success)
gaz_record_success <- mr_gaz_records_by_source(source_success)

source_fail <- mr_gaz_info(info = "sources")$source[15]
source_fail <- as.character(source_fail)
gaz_record_fail <- mr_gaz_records_by_source(source_fail)
#> Error in `resp_check_status()`:
#> ! HTTP 404 Not Found.
```

**Comment by bart-v** [comment]
Which sources? Please provide an example

**Comment by lottepohl** [comment]
[Sources](https://marineregions.org/rest/getGazetteerSources.json/) with `/`  or `[ ]` do not work for the [getGazetteerRecordsBySource](https://marineregions.org/gazetteer.php?p=webservices&type=rest#!/getGazetteerRecordsBySource) webservice when input with their full name, e.g.:
- [Nationaal Instituut voor de Statistiek (NIS) / National Statistical Service](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Nationaal%20Instituut%20voor%20de%20Statistiek%20(NIS)%20%2F%20National%20Statistical%20Service/)
- [Hydrografische Dienst Oostende, Afdeling Waterwegen Kust (1996). Noordzee Vlaamse Banken van Gravelines tot Oostkapelle 1996 [KAART]. Hernieuwde uitgave oktober 1996. Ministerie van de Vlaamse Gemeenschap: Brussel. 1 kaart pp.](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Hydrografische%20Dienst%20Oostende%2C%20Afdeling%20Waterwegen%20Kust%20(1996).%20Noordzee%20Vlaamse%20Banken%20van%20Gravelines%20tot%20Oostkapelle%201996%20%5BKAART%5D.%20Hernieuwde%20uitgave%20oktober%201996.%20Ministerie%20van%20de%20Vlaamse%20Gemeenschap%3A%20Brussel.%201%20kaart%20pp./)

The request works when only a part of the source name without `/` or `[ ]` is input:
- [Nationaal Instituut voor de Statistiek (NIS)](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Nationaal%20Instituut%20voor%20de%20Statistiek%20(NIS)/)
- [Hydrografische Dienst Oostende, Afdeling Waterwegen Kust (1996). Noordzee Vlaamse Banken van Gravelines tot Oostkapelle 1996](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Hydrografische%20Dienst%20Oostende%2C%20Afdeling%20Waterwegen%20Kust%20(1996).%20Noordzee%20Vlaamse%20Banken%20van%20Gravelines%20tot%20Oostkapelle%201996/)

Symbols like `(`, `.`, `:` or `ë` do not cause a 404, see this example that works:
- [Lausch, E. (2000). Atlas van de oceanen: met de dieptekaarten van de wereldzeeën, die de Canadese Hydrografische Dienst heeft gepubliceerd (General Bathymetric Chart of the Oceans, GEBCO). Tirion Uitgevers B.V.: Baarn. ISBN 90-7303-598-8. 264 pp.](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Lausch%2C%20E.%20(2000).%20Atlas%20van%20de%20oceanen%3A%20met%20de%20dieptekaarten%20van%20de%20wereldzee%C3%ABn%2C%20die%20de%20Canadese%20Hydrografische%20Dienst%20heeft%20gepubliceerd%20(General%20Bathymetric%20Chart%20of%20the%20Oceans%2C%20GEBCO).%20Tirion%20Uitgevers%20B.V.%3A%20Baarn.%20ISBN%2090-7303-598-8.%20264%20pp./)

**Comment by bart-v** [comment]
Yes, it's caused by the fact that "/" is the separator for REST API parameters
I guess we'll need something like
`getGazetteerRecordsBySourceID`

**Comment by salvafern** [comment]
@bart-v yes but then I suggest that `getGazetteerSources` also provides the SourceID (currently only `source` and `sourceURL`).

**Comment by bart-v** [comment]
OK, it seems the allowing the "/" or encoded %2F was a setting.
Everything works now.

**Comment by lottepohl** [comment]
> OK, it seems the allowing the "/" or encoded %2F was a setting. Everything works now.

The example request containing `[ ]` still gives an empty response body:
[Hydrografische Dienst Oostende, Afdeling Waterwegen Kust (1996). Noordzee Vlaamse Banken van Gravelines tot Oostkapelle 1996 [KAART]. Hernieuwde uitgave oktober 1996. Ministerie van de Vlaamse Gemeenschap: Brussel. 1 kaart pp.](https://marineregions.org/rest/getGazetteerRecordsBySource.json/Hydrografische%20Dienst%20Oostende%2C%20Afdeling%20Waterwegen%20Kust%20(1996).%20Noordzee%20Vlaamse%20Banken%20van%20Gravelines%20tot%20Oostkapelle%201996%20%5BKAART%5D.%20Hernieuwde%20uitgave%20oktober%201996.%20Ministerie%20van%20de%20Vlaamse%20Gemeenschap%3A%20Brussel.%201%20kaart%20pp./)

**Comment by bart-v** [comment]
Yes, please escape those ] => \] and [
`https://marineregions.org/rest/getGazetteerRecordsBySource.json/Hydrografische%20Dienst%20Oostende%2C%20Afdeling%20Waterwegen%20Kust%20%281996%29.%20Noordzee%20Vlaamse%20Banken%20van%20Gravelines%20tot%20Oostkapelle%201996%20%5C%5BKAART%5C%5D.%20Hernieuwde%20uitgave%20oktober%201996.%20Ministerie%20van%20de%20Vlaamse%20Gemeenschap%3A%20Brussel.%201%20kaart%20pp.`

works
