### ISSUE TITLE
Add WMS visualization helper

### ISSUE THREAD

**Issue by salvafern** [lifewatch/mregions2#7]
via [getGazetteerWMSes](https://marineregions.org/gazetteer.php?p=webservices&type=rest#!/getGazetteerWMSes/getGazetteerWMSes) we can request the WMS link to a single feature, including the necessary fields to perfom some OGC filter. 

We could use this to build a helper function that opens a leaflet viewer that shows the feature. This will help visualizing without needing to actually download the feature. There is an example of this in the [eurobis](https://github.com/lifewatch/eurobis) R package

Also the marine regions products can be accessed via WMS, we could allow the same thing.

To discuss what's the best way (as a method of mr_gaz_mrgid or as a new function helper?).

**Comment by bart-v** [comment]
Applying the filter is not straightforward, as some non-VLIZ layers use different OGC standards/dialects (ArcGIS, MapServer, FILTER, CQL_FILTER, ViewParams, ...)
We have the logic already in the gazetteer for most exceptions.
So it would be best to expose that, instead of trying it again from scratch.

**Comment by salvafern** [comment]
Do you mean that the web service explicitly says what filter should be applied? (e.g. OGC / ArcGIS ...)

**Comment by bart-v** [comment]
Not always, maybe partially in the GetCapabilities request
In many cases is was trail and error :)

**Comment by salvafern** [comment]
We will then look into exposing the type of filter that has to be applied via the webservice - I can pick that up in R to apply the specific filter in the WMS call

**Comment by bart-v** [comment]
This is now overruled by the `getGazetteerGeometries()` function
All the OGC filtering logic is now applied internally, and you can just fetch the geometry from that function

**Comment by LennertSchepers** [comment]
I think the original aim of this issue (using the WMS) was to avoid the download of potentially large geometries if the user just wants to visualize them.  `getGazetteerGeometries()` doesn't solve that.
(for internal reference: I had implemented the filter logic (ArcGIS, MapServer, FILTER) in the dev version of the gazetteer shiny app, not sure if this is still up to date)

**Comment by bart-v** [comment]
A single geometry is rarely large, except the grouped standards. So maybe 5-10 cases.

I think using the geometry like this is much more stable than trying to maintain all the query options, as you mention yourself "not sure if this is still up to date"
