### ISSUE TITLE
mregions2 OOP: add elements to existing class

### ISSUE THREAD

**Issue by lottepohl** [lifewatch/mregions2#8]
- enable user to add elements to the `MarineRegion` object generator class for customisation
- create wrapper function to avoid contact of users with R6

#5 I have written a class `MarineRegion` and a wrapper function for users to create objects of that class.
In R6, you can add private/public elements to the class in the aftermath by [`<class_name>$set()`](https://r6.r-lib.org/articles/Introduction.html#adding-members-to-an-existing-class). This might be a starting point for adding customisation possibilities for users later.

Right now, I don't know how to solve the following thing. Just to document, there are certainly solutions for this.
 - `<class_name>$set()` cannot access elements of the object generator class. This prevents passing e.g. the mrgid (`private$..mrgid`) to the function.

**Comment by lottepohl** [comment]
@marc-portier @bart-v maybe you can help since this might be a structural question that not only occurs in R OOP

**Comment by salvafern** [comment]
We decided to not use R6
