### ISSUE TITLE
GeoObjects with `placeType == "ICES Ecoregion"` seem to have wrong CRS

### ISSUE THREAD

**Issue by lottepohl** [lifewatch/mregions2#9]
When comparing GeoObjects of regions in the same area of placeType "IHO Sea Area" and "ICES Ecoregion", the latter are not mapped correctly.
Examples: **Adriatic Sea** (MRGIDs: IHO Sea Area = 3314 and ICES Ecoregion = 36314) and **Bay of Biscay** (MRGIDs: IHO Sea Area = 2359, ICES Ecoregion = 36311)

``` r
library(mregions2)
library(mapview)
library(magrittr)

adria <- mr_gaz_records_by_name("Adriatic Sea")
adria_iho <- subset(adria, placeType == "IHO Sea Area")$MRGID %>% 
  mr_gaz_record()
adria_ices <- subset(adria, placeType == "ICES Ecoregion")$MRGID %>%
  mr_gaz_record()

mapview(list(adria_iho$geom, adria_ices$geom))
```

![](https://i.imgur.com/UiPoxn8.png)

``` r
biscay <- mr_gaz_records_by_name("Bay of Biscay")
biscay_iho <- subset(biscay, placeType == "IHO Sea Area")$MRGID %>% 
  mr_gaz_record()
biscay_ices <- subset(biscay, placeType == "ICES Ecoregion")$MRGID %>%
  mr_gaz_record()

mapview(list(biscay_iho$geom, biscay_ices$geom))
```

![](https://i.imgur.com/hxh7JeX.png)

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bart-v** [comment]
MRGID 36314 resolves to this WFS call at ICES

https://gis.ices.dk/gis/services/ICES_reference_layers/ICES_Ecoregions/MapServer/WFSServer?service=WFS&request=GetFeature&typeName=ICES_reference_layers_ICES_Ecoregions:ICES_Ecoregions&FILTER=%3CFilter%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3Eecoregion%3C/PropertyName%3E%3CLiteral%3EAdriatic%20Sea%3C/Literal%3E%3C/PropertyIsEqualTo%3E%3C/Filter%3E&outputFormat=GEOJSON

This indeed seems to produce "incorrect" JSON.
I rather think of a swapped la/lon instead of an incorrect CRS

**Comment by bart-v** [comment]
A simple fix is to add
`&srsName=urn:ogc:def:crs:EPSG::4326`
to the URL

This seems to swap the lat & long
`https://gis.ices.dk/gis/services/ICES_reference_layers/ICES_Ecoregions/MapServer/WFSServer?service=WFS&request=GetFeature&typeName=ICES_reference_layers_ICES_Ecoregions:ICES_Ecoregions&FILTER=<Filter><PropertyIsEqualTo><PropertyName>ecoregion</PropertyName><Literal>Adriatic Sea</Literal></PropertyIsEqualTo></Filter>&outputFormat=GEOJSON&srsName=urn:ogc:def:crs:EPSG::4326`

Source: https://github.com/mapserver/mapserver/issues/5186#issuecomment-151532797

**Comment by bart-v** [comment]
ICES geometry refreshed, should be fixed.
Can you check?

**Comment by lottepohl** [comment]
> ICES geometry refreshed, should be fixed. Can you check?

I checked, it works.

``` r
library(mregions2)
library(mapview)
biscay <- mr_gaz_records_by_name("Bay of Biscay")
biscay_iho <- biscay[1,]$MRGID %>% mr_gaz_record()
biscay_ices <- biscay[3,]$MRGID %>% mr_gaz_record()
mapview(list(biscay_iho, biscay_ices))
```

![](https://i.imgur.com/tE97jZG.png)

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by salvafern** [comment]
Thanks for spotting @whaleshark99 !
